### ISSUE TITLE
how to change markdown theme?

### ISSUE THREAD

**Issue by mibrahimdev** [a3ammar/arabic-jekyll#2]
thanks for support Arabic language, but I need to know how to change markdown theme and colors specially code blocks.

**Comment by a3ammar** [comment]
Hey!
You can find all the CSS styles that control how the code blocks looks can be found here https://github.com/a3ammar/arabic-jekyll/blob/c431a52c11c6e36a3859006aed692e96fb487a32/_sass/_highlights.scss#L3 look for the same file in your fork.

I recommend you right click on a code block in your browser and choose “Inspect Element” and you can change the style for it and once you’re satisfied copy them to that file.

**Comment by mibrahimdev** [comment]
oh nice, I have another question please, could jekyllnow theme be bi language blog, I need to blog in arabic and english

**Comment by a3ammar** [comment]
Yes it could but this specific theme was not designed with multiple languages in mind, maybe in the future I will redo it with that in mind.

**Comment by mibrahimdev** [comment]
thanks .. but please let me know if you did it. I don't have enough knowledge to do it myself.
