### ISSUE TITLE
قولب داعمة للغة العربية

### ISSUE THREAD

**Issue by faalobaidli** [a3ammar/arabic-jekyll#3]
السلام عليكم اخ عمار

في البداية شكرا لك على هذه المقالة والجهد الرائع لةعم التةوين بجيكل باللغة العربية. بحثت كثيرا عن كيفية التدوين للغات المكتوبة من اليمين الى اليسار حتى وجدت صفحتك.

كنت اظن ان مسألة تحويل القوالب سهلة بمجرد اضافة بعض السطور الى اي قالب لتحويل اتجاهه. مثلا:
dir: rtl

لكن اتضح لي ان الامر اكثر تعقيدا وأتمنى منك المساعدة حيث أنني أنوي استخدام: http://jekyllthemes.org/themes/jekyll-theme-console/
على سبيل المثال

شكرا مقدما

**Comment by a3ammar** [comment]
وعليكم السلام،

طريقة تحويل اي قالب للعربية ليست معقدة، ولكن تتطلب بعض من التعديلات على الـcss:

- [اضافة `lang: ar` على `<body>`](https://github.com/barryclark/jekyll-now/compare/master...a3ammar:master#diff-2c19d9859b055d0302043d0fa2833e3fR21)
- [تعديل الخط](https://github.com/barryclark/jekyll-now/compare/master...a3ammar:master#diff-1fc2d5dfc8847c48d37266ee0b981b01R1)
- [تعديل `direction` على `<html>` ](https://github.com/barryclark/jekyll-now/compare/master...a3ammar:master#diff-f75cdbcea8034badbb1b7f8097fcb138R18)
- [واخيرا تعديل `float: left`، `marge-left`، او `padding-left` الى `*-right`](https://github.com/barryclark/jekyll-now/compare/master...a3ammar:master#diff-f75cdbcea8034badbb1b7f8097fcb138L82)

بالتوفيق.

**Comment by faalobaidli** [comment]
شكرا لك على الرد اخي
بالنسبة للقالب console الذي اشرت اليه استبدلت كل كلمة left بright والعكس  في ملف _sass/base.scss
طبعا بالاضافة لبقية التوجيهات التي ذكرتها
للفائدة
