### ISSUE TITLE
Is it possible to use arabic-jekyll to blog in two languages?

### ISSUE THREAD

**Issue by 0xMH** [a3ammar/arabic-jekyll#4]
I'd like to start using arabic-jekyll as my go-to for blogging but I had to ask first. Is it possible to use it/or any other jekyll theme to blog Both in Arabic and English?

**Comment by a3ammar** [comment]
Yes, you can define a new layout for English and specify it in the post's [frontmatter](https://jekyllrb.com/docs/front-matter/)
