### ISSUE TITLE
writing arabic on github

### ISSUE THREAD

**Issue by bachirmath** [a3ammar/arabic-jekyll#5]
Hi, Im trying to write a page in arabic on github, the problem is that when I write on markdown, it looks fine, but when I take a look at the page, the direction isnt right, I wish you could give us a siple example on how you wrote your page on Jeykll

**Comment by a3ammar** [comment]
Hello,

See tutorial's sourec code https://raw.githubusercontent.com/a3ammar/arabic-jekyll/gh-pages/_posts/2017-1-6-readme.md
