### ISSUE TITLE
Rendering is inconsistent

### ISSUE THREAD

**Issue by bachirmath** [a3ammar/arabic-jekyll#7]
Hello, 

I hope you are doing well, I forked your project, and added somethings, like Mathjax to render math, and some other stuff, and here is my problem, the page renders perfectly under Firefox, but under different browsers, the math equations are Big, really big, if you have an advice on how to make it consistent, I would be thankful.

https://github.com/bachirmath/bachirmath.github.io

 Ps: from what I read I thing its a css styling thing which I didn't find a way to solve

Thank you for your work

**Comment by a3ammar** [comment]
Something is setting the the font-size to a large value `161.1%` I recommend you don't use percentage based values instead use fixed value like `font-size: 26px`

**Comment by bachirmath** [comment]
> Something is setting the the font-size to a large value `161.1%` I recommend you don't use percentage based values instead use fixed value like `font-size: 26px`

could you tell me where the change should be, which file I mean

**Comment by a3ammar** [comment]
I'm not familiar with MathJax but I think adding this to [style.scss](https://github.com/bachirmath/bachirmath.github.io/blob/master/style.scss) will set the font size correctly. Experiment with the values until you are satisfied.

```css
.MathJax {
    font-size: 30px !important;
}
```

Out of curiosity what browser did not render the page correctly?

**Comment by bachirmath** [comment]
Thank you so much, it works fine now

I tested it before on chrome and  brave, and it had that issue, but it was normal on Firefox
But with your solution, its consistent on all browsers, thank you again

**Comment by a3ammar** [comment]
Anytime and good luck!
